
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - meshery.layer5.io
  resources:
  - meshsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meshery.layer5.io
  resources:
  - meshsyncs/status
  verbs:
  - get
  - patch
  - update
